services:
  backend:
    build:
      context: ./backend
    restart: always
    environment:
      HOST: ${BACKEND_HOST:?Variable not set}
      PORT: ${BACKEND_PORT:?Variable not set}
      SQLALCHEMY_DATABASE_URI: ${SQLALCHEMY_DATABASE_URI?Variable not set}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${BACKEND_PORT}/health"]
      timeout: 5s
      interval: 10s
      retries: 5
