[project]
name = "short-url-backend"
version = "0.0.1"
description = "The REST API backend of short-url"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]==0.115.11",
    "uvicorn[standard]==0.34.0"
]

[project.optional-dependencies]
dev-dependencies = []
